name: 'Git Releaser'
description: 'Runs git-releaser'

inputs:
  repository:
    description: 'GitHub repository'
    required: true
  actor:
    description: 'GitHub actor'
    required: true
  token:
    description: 'GitHub token'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
